<?php
return [
    'general'=>[
        'user'=>[
            'register'=>'on',
            'login'=>'on',
            'delete_user'=>'on'
        ],
        'api'=>[
            'youtube_api'=>'',
            'dailymotion_verification_id'=>'',
            'twitch_client_id'=>'',
        ],
        'main'=>[
            'upload_video'=>'on',
            'import_video'=>'on',
            'auto_play'=>'on',
            'embed_video'=>'on',
            'history_system'=>'on',
            'article_system'=>'on',
            'down_system'=>'on',
            'import_facebook_video'=>'on',
            'import_twitch_video'=>'on',
            'donate_to_channel'=>'on',
            'approve_video_before_publishing'=>'on',
            'two_factor_setting'=>'on',
            'popular_channel'=>'on',
            'geo_blocking'=>'on',
            'all_create_article'=>'on',
            'movie_video'=>'on',
        ],
        'comment'=>[
            'comment_system'=>'both',
            'default_show_comment'=>10
        ],
        'upload'=>[
            'upload_system_type'=>'all',
            'free_user_upload_limit'=>'1024',
            'pro_user_upload_limit'=>'10240',
        ],
        'video'=>[
            'video_pagination_limit'=>20
        ],
        'paid_video'=>[
            'paid_video_system'=>'on',
            'who_can_sell_video'=>'all',
            'auto_approve_sell_video'=>'on',
        ]

    ],
    'website'=>[
        'website'=>[
            'site_title'=>'站点标题',
            'site_name'=>'站点名称',
            'site_keyword'=>'站点关键词',
            'site_email'=>'站点邮箱',
            'site_description'=>'站点描述',
        ],
        'other'=>[
            'max_upload_size'=>'1024',
            'seo_link'=>'on',
            'recaptcha'=>'on',
            'recaptcha_id'=>'',
            'google_analytics_id'=>''
        ]
    ],
    'email'=>[
        'server_type'=>'server',
        'smtp_host'=>'host',
        'smtp_username'=>'username',
        'smtp_password'=>'password',
        'smtp_port'=>'21',
        'smtp_encryption'=>'ssl',
    ],
    'social_login'=>[
        'facebook'=>[
            'switch'=>'on',
            'facebook_api_id'=>'facebook_api_id',
            'facebook_api_key'=>'facebook_api_key',
        ],
        'twitter'=>[
            'switch'=>'on',
            'twitter_api_id'=>'twitter_api_id',
            'twitter_api_key'=>'twitter_api_key',
        ],
        'google'=>[
            'switch'=>'off',
            'google_api_id'=>'google_api_id',
            'google_api_key'=>'google_api_key',
        ]
    ],
    'qiniu_ftp'=>[
        'qiniu'=>[
            'qiniu_key'=>'YoUowhNgyw6OyLTwRANi8NRTr3fRuAb_z3_N_pxp',
            'qiniu_secret_key'=>'zMmHURXnnLIFs84CYWxD0EKR4qgE-qJprVzv8iPQ',
            'bucket'=>[
                'subtitle'=>[
                    '127.0.0.1'=>[
                        'bucket_name'=>'',
                        'domain'=>'',
                        'ip'=>'127.0.0.1'
                    ],
                    '127.0.0.1'=>[
                        'bucket_name'=>'',
                        'domain'=>'',
                        'ip'=>'127.0.0.1'
                    ]
                ]
            ]
        ]
    ]


];